version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rag_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-azera}
      POSTGRES_DB: ${DB_NAME:-Rag_it}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: rag_mlflow
    restart: always
    ports:
      - "5000:5000"
    command: mlflow ui --host 0.0.0.0 --port 5000
    volumes:
      - mlruns_data:/mlruns

  app:
    image: rag_it_assistant_img
    pull_policy: never
    build: .
    container_name: rag_app
    working_dir: /app  # <--- ADD THIS LINE
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - mlflow
    volumes:
      - .:/app

volumes:
  postgres_data:
  mlruns_data:
