apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: default
type: Opaque
data:
  HF_TOKEN: 
  GOOGLE_API_KEY: 
  POSTGRES_USER: 
  POSTGRES_PASSWORD: 
  POSTGRES_DB: 
  DATABASE_URL: 
  SECRET_KEY: 